server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: ["http://elasticsearch:9200"]

xpack.monitoring.ui.container.elasticsearch.enabled: false
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "fhjsunfkjhskjfhsjkfhsjkfhsjkfhsjkf"

logging.appenders.file.type: file
logging.appenders.file.fileName: /var/log/kibana.log
logging.appenders.file.layout.type: json

logging.root.appenders: [default, file]